### ISSUE TITLE
Flask exception thrown 

### ISSUE THREAD

**Issue by andrewkreid** [andrewkreid/mydetic#25]
Happens when requesting more than one memory at a time from Android

```
[Sat Jul 23 05:18:51 2016] [error] Traceback (most recent call last):
[Sat Jul 23 05:18:51 2016] [error]   File "build/bdist.linux-x86_64/egg/mydetic/flask_server.py", line 368, in create_app
[Sat Jul 23 05:18:51 2016] [error]     @app.route('/')
[Sat Jul 23 05:18:51 2016] [error]   File "/home/ec2-user/mydetic-env/lib/python2.7/site-packages/flask/app.py", line 1013, in decorator
[Sat Jul 23 05:18:51 2016] [error]     self.add_url_rule(rule, endpoint, f, **options)
[Sat Jul 23 05:18:51 2016] [error]   File "/home/ec2-user/mydetic-env/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
[Sat Jul 23 05:18:51 2016] [error]     return f(self, *args, **kwargs)
[Sat Jul 23 05:18:51 2016] [error]   File "/home/ec2-user/mydetic-env/lib/python2.7/site-packages/flask/app.py", line 984, in add_url_rule
[Sat Jul 23 05:18:51 2016] [error]     'existing endpoint function: %s' % endpoint)
[Sat Jul 23 05:18:51 2016] [error] AssertionError: View function mapping is overwriting an existing endpoint function: index
[Sat Jul 23 05:18:51 2016] [error] Traceback (most recent call last):
[Sat Jul 23 05:18:51 2016] [error]   File "/var/www/mydetic/mydetic.wsgi", line 24, in application
[Sat Jul 23 05:18:51 2016] [error]     return _application(req_environ, start_response)
[Sat Jul 23 05:18:51 2016] [error] TypeError: 'NoneType' object is not callable
```

**Comment by andrewkreid** [comment]
Fixed in a0515afdcea5e594ce10f398a368e03b26d5a2d1
